"""empty message

Revision ID: ca67ce1c2e02
Revises: c78d2bc2b8a7
Create Date: 2017-03-31 18:53:53.604864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca67ce1c2e02'
down_revision = 'c78d2bc2b8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('photo', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'photo')
    # ### end Alembic commands ###
